# Sandbox base image
FROM safoinext/zenml-sandbox:latest

# Project metadata
LABEL project_name="zencoder"
LABEL project_version="0.1.0"

# Install project-specific dependencies
RUN pip install --no-cache-dir \
    "zenml[server]>=0.73.0" \
    "packaging" \
    "notebook" \
    "datasets" \
    "nbformat" \
    "pandas" \
    "PyGithub" \
    "ninja" \
    "kfp>=2.6.0" \
    "gcsfs" \
    "google-cloud-secret-manager" \
    "google-cloud-container>=2.21.0" \
    "google-cloud-artifact-registry>=1.11.3" \
    "google-cloud-storage>=2.9.0" \
    "google-cloud-aiplatform>=1.34.0" \
    "google-cloud-build>=3.11.0" \
    "kubernetes" \
    "git+https://github.com/huggingface/transformers" \
    "git+https://github.com/huggingface/accelerate" \
    "git+https://github.com/huggingface/peft" \
    "trl" \
    "huggingface-hub" \
    "bitsandbytes" \
    "evaluate" \
    "einops" \
    "wandb>=0.12.12" \
    "tiktoken" \
    "deepspeed" \
    "tqdm==4.65.0" \
    "safetensors"

# Set workspace directory
WORKDIR /workspace

# Clone only the project directory and reorganize
RUN git clone --depth 1 https://github.com/zenml-io/zenml-projects.git /tmp/zenml-projects && \
    cp -r /tmp/zenml-projects/zencoder/* /workspace/ && \
    rm -rf /tmp/zenml-projects

# Create a template .env file for API keys
RUN echo "GH_ACCESS_TOKEN=YOUR_GH_KEY_HERE" && \
    echo "HF_TOKEN=YOUR_HUGGINGFACE_TOKEN_HERE" && \
    echo "OPENAI_API_KEY=YOUR_OPENAI_KEY_HERE" > .env

# Create a .vscode directory and settings.json file
RUN mkdir -p /workspace/.vscode && \
    echo '{\n'\
    '  "workbench.colorTheme": "Default Dark Modern"\n'\
    '}' > /workspace/.vscode/settings.json


