# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow
      - matplotlib
      - pillow
      - numpy

# configuration of the Model Control Plane
model:
  name: breast_cancer_classifier
  license: Apache 2.0
  description: A breast cancer classifier
  tags: ["breast_cancer", "classifier"]
