enable_cache: False

# environment configuration
settings:
  docker:
    parent_image: "zenmldocker/prepare-release:base-0.68.0"
    requirements:
      - langchain-community
      - ratelimit
      - langchain>=0.0.325
      - langchain-openai
      - pgvector
      - psycopg2-binary
      - beautifulsoup4
      - unstructured
      - pandas
      - numpy
      - sentence-transformers>=3
      - transformers[torch]
      - litellm
      - ollama
      - tiktoken
      - umap-learn
      - matplotlib
      - pyarrow
      - rerankers[flashrank]
      - datasets
      - torch
