# environment configuration
settings:
  docker:
    requirements:
      - unstructured
      - sentence-transformers>=3
      - pgvector
      - datasets
      - litellm
      - numpy
      - psycopg2-binary
      - tiktoken
      - ratelimit
    environment:
      ZENML_PROJECT_SECRET_NAME: llm_complete
      ZENML_ENABLE_RICH_TRACEBACK: FALSE
      ZENML_LOGGING_VERBOSITY: INFO

steps:
  url_scraper:
    parameters:
      docs_url: https://docs.zenml.io
  generate_embeddings:
    step_operator: "terraform-gcp-6c0fd52233ca"
    settings:
      step_operator.vertex:
        accelerator_type: "NVIDIA_TESLA_P100"
        accelerator_count: 1
        machine_type: "n1-standard-8"

# configuration of the Model Control Plane
model:
  name: finetuned-zenml-docs-embeddings
  license: Apache 2.0
  description: Finetuned LLM on ZenML docs
  tags: ["rag", "finetuned"]