# enable_cache: False

# environment configuration
settings:
  docker:
    requirements:
      - langchain-community
      - ratelimit
      - langchain>=0.0.325
      - langchain-openai
      - pgvector
      - psycopg2-binary
      - beautifulsoup4
      - unstructured
      - pandas
      - numpy
      - sentence-transformers>=3
      - transformers
      - litellm
      - ollama
      - tiktoken
      - umap-learn
      - matplotlib
      - pyarrow
      - rerankers[flashrank]
      - datasets
      - torch
      - distilabel
    environment:
      ZENML_SUPABASE_SECRET_NAME: supabase_postgres_db
      ZENML_OPENAI_SECRET_NAME: openai
