# enable_cache: False

# environment configuration
settings:
  docker:
    requirements:
      - langchain-community
      - ratelimit
      - langchain>=0.0.325
      - langchain-openai
      - pgvector
      - psycopg2-binary
      - beautifulsoup4
      - unstructured
      - pandas
      - numpy
      - sentence-transformers>=3
      - transformers
      - litellm
      - ollama
      - tiktoken
      - umap-learn
      - matplotlib
      - pyarrow
      - rerankers[flashrank]
      - datasets
      - torch
      - distilabel
    environment:
      ZENML_PROJECT_SECRET_NAME: llm_complete


# configuration of the Model Control Plane
model:
  name: finetuned-zenml-docs-embeddings
  version: latest
  license: Apache 2.0
  description: Finetuned LLM on ZenML docs
  tags: ["rag", "finetuned"]
