DATASET_NAME = "ships"
LABELED_DATASET_NAME = "ship_od_dataset"
DATASET_DIR = "data/ships/subset"
TRAINED_MODEL_NAME = "Trained_YOLO"
PREDICTIONS_DATASET_ARTIFACT_NAME = "predictions_dataset_json"
ZENML_MODEL_NAME = "ShipDetector"
