# Sandbox base image
FROM zenmldocker/zenml-sandbox:latest

# Project metadata
LABEL project_name="omni-reader"
LABEL project_version="0.1.0"

# Install project-specific dependencies
RUN pip install --no-cache-dir \
    "instructor" \
    "jiwer" \
    "jiter" \
    "importlib-metadata<7.0,>=1.4.0" \
    "litellm" \
    "mistralai==1.0.3" \
    "numpy<2.0,>=1.9.0" \
    "openai==1.69.0" \
    "Pillow==11.1.0" \
    "polars-lts-cpu==1.26.0" \
    "pyarrow>=7.0.0" \
    "python-dotenv" \
    "streamlit==1.44.0" \
    "pydantic>=2.8.2,<2.9.0" \
    "tqdm==4.66.4" \
    "zenml>=0.80.0"

# Set workspace directory
WORKDIR /workspace

# Clone only the project directory and reorganize
RUN git clone --depth 1 https://github.com/zenml-io/zenml-projects.git /tmp/zenml-projects && \
    cp -r /tmp/zenml-projects/omni-reader/* /workspace/ && \
    rm -rf /tmp/zenml-projects

# Create a template .env file for API keys
RUN echo "OPENAI_API_KEY=YOUR_OPENAI_API_KEY" && \
    echo "MISTRAL_API_KEY=YOUR_MISTRAL_API_KEY" > .env

# Create a .vscode directory and settings.json file
RUN mkdir -p /workspace/.vscode && \
    echo '{\n'\
    '  "workbench.colorTheme": "Default Dark Modern"\n'\
    '}' > /workspace/.vscode/settings.json


# Set environment variables for compatibility and performance
ENV POLARS_SKIP_CPU_CHECK=1
