[project]
name = "sonicscribe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-aiplatform>=1.86.0",
    "litellm>=1.63.14",
    "rich>=13.9.4",
    "zenml>=0.80.0",
]
