enable_cache: False
extra:
  tags: zenml-projects
settings:
  docker:
    required_integrations:
      - aws
      - sklearn
      - mlflow
      - evidently
      - kubeflow
    requirements:
      - nba-api
steps:
  trainer:
      experiment_tracker: mlflow_tracker
