model:
  name: llm_lora-Mistral-7B-Instruct-v0.1
  description: "Fine-tune `mistralai/Mistral-7B-Instruct-v0.1`."
  tags:
    - llm
    - lora
    - mistralai/Mistral-7B-Instruct-v0.1

settings:
  docker:
    parent_image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime

steps:
  evaluate:
    enable_step_logs: False
    parameters:
      config:
        model_repo: mistralai/Mistral-7B-Instruct-v0.1
        from_safetensors: False
        adapter_repo: 
        precision: bf16-true