model:
  name: llm_lora-Mistral-7B-Instruct-v0.1
  description: "Fine-tune `mistralai/Mistral-7B-Instruct-v0.1`."
  tags:
    - llm
    - lora
    - mistralai/Mistral-7B-Instruct-v0.1

steps:
  feature_engineering:
    enable_step_logs: False
    parameters:
      config:
        model_repo: mistralai/Mistral-7B-Instruct-v0.1
        dataset_name: csv
        prepare_kwargs:
          # REQUIRED: Path the the .csv file containing the data. Format must be as described here
          # https://github.com/Lightning-AI/litgpt/blob/main/tutorials/prepare_dataset.md#preparing-custom-datasets-from-a-csv-file
          csv_path: null
