enable_cache: False

# pipeline configuration
parameters:
  dataset_name: "ship_detection_gcp" # "ship_detection"

# Configuration of the Model Control Plane
model:
  name: ShipDetector
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
