enable_cache: False

settings:
  docker:
    apt_packages:
      - ffmpeg
      - libsm6
      - libxext6
      - libcurl4
    required_integrations:
      - gcp
      - github
    requirements:
      - ultralytics
      - fiftyone

steps:
  create_fiftyone_dataset:
    enable_cache: False
    enable_step_logs: False
    parameters:
      inference_data_source:   # Insert your bucket path here where the inference images live e.g. "gs://foo/bar"

# configuration of the Model Control Plane
model:
  name: ShipDetector
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
  version: production