enable_cache: False

settings:
  docker:
    apt_packages:
      - ffmpeg
      - libsm6
      - libxext6
      - libcurl4
    required_integrations:
      - gcp # For AWS use "s3" instead of "gcp"
      - github
    requirements:
      - ultralytics
      - fiftyone

steps:
  create_fiftyone_dataset:
    enable_cache: False
    enable_step_logs: False
    parameters:
      inference_data_source:   # Set this to the path to a data source, for example "gs://zenml-20219041791-054405/ship_detection_ds"

# configuration of the Model Control Plane
model:
  name: ShipDetector
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
  version: production