parameters:
  model_checkpoint: yolov8l.pt

steps:
  load_model:
    enable_cache: True
  train_model:
    enable_cache: False
    parameters:
      data_source: "gs://zenml-internal-artifact-store/label_studio_cv_webinar"
      batch_size: 16
      imgsz: 640
      epochs: 30

settings:
  docker:
    apt_packages:
      - ffmpeg
      - libsm6
      - libxext6
    required_integrations:
      - gcp
      - github
    requirements:
      - ultralytics

# configuration of the Model Control Plane
model:
  name: ShipDetector
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
  version: staging
