parameters:
  model_checkpoint: yolov8l.pt

settings:
  docker:
    apt_packages:
      - ffmpeg
      - libsm6
      - libxext6
    required_integrations:
      - gcp
      - github
    requirements:
      - ultralytics

steps:
  load_model:
    enable_cache: True
  train_model:
    enable_cache: False
    step_operator: gcp_a100
    enable_step_logs: False
    parameters:
      data_source: "gs://zenml-internal-artifact-store/label_studio_cv_webinar"
      batch_size: 8
      imgsz: 480
      epochs: 5000
      is_quad_gpu_env: True
    settings:
      step_operator.vertex:
        accelerator_type: NVIDIA_TESLA_T4 # NVIDIA_TESLA_A100 # see https://cloud.google.com/vertex-ai/docs/reference/rest/v1/MachineSpec#AcceleratorType
        accelerator_count: 4
        disk_size_gb: 25
      docker:
        parent_image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
        required_integrations:
          - gcp
          - github
        requirements:
          - ultralytics
          - zenml
          - numpy
        environment:
          MKL_SERVICE_FORCE_INTEL: 1


# configuration of the Model Control Plane
model:
  name: ShipDetector
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
  version: staging