enable_cache: True
extra:
  tags: zenml-projects
settings:
  docker:
    required_integrations:
      - facets
      - lightgbm
      - xgboost
    requirements:
      - statsmodels
      - optuna
      - statsmodels
      - feature_engine
