enable_cache: False

# environment configuration
settings:
  docker:
    requirements:
      - unstructured
      - sentence-transformers>=3
      - pgvector
      - datasets
      - litellm
      - numpy
      - psycopg2-binary
      - tiktoken
      - ratelimit
      - rerankers
      - pygithub
      - rerankers[flashrank]
      - matplotlib
      - elasticsearch

    environment:
      ZENML_PROJECT_SECRET_NAME: llm_complete
      ZENML_ENABLE_RICH_TRACEBACK: FALSE
      ZENML_LOGGING_VERBOSITY: INFO
    python_package_installer: "uv"
steps:
  url_scraper:
    parameters:
      docs_url: https://docs.zenml.io
      use_dev_set: false
#  generate_embeddings:
#    step_operator: "sagemaker"
#    settings:
#      step_operator.sagemaker:
#        accelerator_count: 1
#        accelerator_type: NVIDIA_TESLA_A100