apiVersion: v1
kind: Service
metadata:
  labels:
    app: placeholder
  name: placeholder
spec:
  ports:
  - name: http        # Changed from 'predict' to 'http' for clarity
    port: 80          # External port exposed by LoadBalancer
    targetPort: 3000  # Internal container port
  selector:
    app: placeholder
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: placeholder
  name: placeholder
spec:
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - image: placeholder
        name: placeholder
        ports:
        - containerPort: 3000