# Sandbox base image
FROM safoinext/zenml-sandbox:latest

# Project metadata
LABEL project_name="llm-complete-guide"
LABEL project_version="0.1.0"

# Install project-specific dependencies
RUN pip install --no-cache-dir \
    "git+https://github.com/zenml-io/zenml.git@develop#egg=zenml[server] # will work for zenml>=0.75.0" \
    "ratelimit" \
    "pgvector" \
    "psycopg2-binary" \
    "beautifulsoup4" \
    "unstructured" \
    "pandas" \
    "openai" \
    "numpy" \
    "sentence-transformers>=3" \
    "transformers" \
    "litellm" \
    "ollama" \
    "tiktoken" \
    "umap-learn" \
    "matplotlib" \
    "pyarrow" \
    "rerankers[flashrank]" \
    "datasets" \
    "torch" \
    "gradio>=5.13.0" \
    "huggingface-hub" \
    "elasticsearch" \
    "tenacity" \
    "langfuse" \
    "pinecone"

# Set workspace directory
WORKDIR /workspace

# Clone only the project directory and reorganize
RUN git clone --depth 1 https://github.com/zenml-io/zenml-projects.git /tmp/zenml-projects && \
    cp -r /tmp/zenml-projects/llm-complete-guide/* /workspace/ && \
    rm -rf /tmp/zenml-projects

# Create a template .env file for API keys
RUN echo "ANTHROPIC_API_KEY=YOUR_ANTHROPIC_KEY_HERE" && \
    echo "GH_ACCESS_TOKEN=YOUR_GH_KEY_HERE" && \
    echo "SUPABASE_USER=YOUR_SUPABASE_KEY_HERE" && \
    echo "ZENML_HF_USERNAME=YOUR_ZENML_KEY_HERE" && \
    echo "SUPABASE_PORT=YOUR_SUPABASE_KEY_HERE" && \
    echo "LANGFUSE_HOST=YOUR_LANGFUSE_KEY_HERE" && \
    echo "AWS_REGION=YOUR_AWS_KEY_HERE" && \
    echo "SUPABASE_HOST=YOUR_SUPABASE_KEY_HERE" && \
    echo "ZENML_PROJECT_SECRET_NAME=YOUR_ZENML_KEY_HERE" && \
    echo "LANGFUSE_SECRET_KEY=YOUR_LANGFUSE_KEY_HERE" && \
    echo "HF_TOKEN=YOUR_HUGGINGFACE_TOKEN_HERE" && \
    echo "OPENAI_API_KEY=YOUR_OPENAI_KEY_HERE" && \
    echo "LANGFUSE_PUBLIC_KEY=YOUR_LANGFUSE_KEY_HERE" && \
    echo "PINECONE_API_KEY=YOUR_PINECONE_KEY_HERE" && \
    echo "SUPABASE_PASSWORD=YOUR_SUPABASE_KEY_HERE" && \
    echo "ZENML_STORE_API_KEY=YOUR_ZENML_KEY_HERE" && \
    echo "ZENML_STORE_URL=YOUR_ZENML_KEY_HERE" && \
    echo "ZENML_HF_SPACE_NAME=YOUR_ZENML_KEY_HERE" > .env

# Create a .vscode directory and settings.json file
RUN mkdir -p /workspace/.vscode && \
    echo '{\n'\
    '  "workbench.colorTheme": "Default Dark Modern"\n'\
    '}' > /workspace/.vscode/settings.json


# Set environment variables for compatibility and performance
ENV TOKENIZERS_PARALLELISM=false
