name: Build and Push Project Sandbox Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - "_assets/**"
      - ".github/**"
      - ".gitignore"
      - ".gitmodules"
      - ".typos.toml"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "generate_sandbox_dockerfile.py"
      - "generate_zenml_project.py"
      - "LICENSE"
      - "pyproject.toml"
      - "README.md"

  workflow_dispatch:
    inputs:
      project:
        description: "Project to build (leave empty to detect from changed files)"
        required: false
        default: ""

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Detect changed projects
        id: set-matrix
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.project }}" ]; then
              # Use the manually specified project
              PROJECTS="[\"${{ github.event.inputs.project }}\"]"
            else
              # Auto-detect changed files (same logic as push events)
              CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
              CHANGED_DIRS=$(echo "$CHANGED_FILES" | grep -o "^[^/]*" | sort -u | grep -v "^$")
              PROJECTS_WITH_DOCKERFILE=$(find . -maxdepth 2 -name "Dockerfile.sandbox" -not -path "*/\.*" | xargs dirname | xargs basename -a)
              PROJECTS="["
              COMMA=""
              for DIR in $CHANGED_DIRS; do
                if echo "$PROJECTS_WITH_DOCKERFILE" | grep -q "^$DIR$"; then
                  PROJECTS="${PROJECTS}${COMMA}\"${DIR}\""
                  COMMA=","
                fi
              done
              PROJECTS="${PROJECTS}]"
            fi
          else
          # Original push event logic
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | grep -o "^[^/]*" | sort -u | grep -v "^$")
          PROJECTS_WITH_DOCKERFILE=$(find . -maxdepth 2 -name "Dockerfile.sandbox" -not -path "*/\.*" | xargs dirname | xargs basename -a)
          PROJECTS="["
          COMMA=""
          for DIR in $CHANGED_DIRS; do
            if echo "$PROJECTS_WITH_DOCKERFILE" | grep -q "^$DIR$"; then
              PROJECTS="${PROJECTS}${COMMA}\"${DIR}\""
              COMMA=","
            fi
          done
          PROJECTS="${PROJECTS}]"
          fi
          echo "matrix=$PROJECTS" >> $GITHUB_OUTPUT
          echo "Projects to build: $PROJECTS"

  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for Dockerfile.sandbox
        id: check-dockerfile
        run: |
          if [ -f "${{ matrix.project }}/Dockerfile.sandbox" ]; then
            echo "dockerfile_exists=true" >> $GITHUB_OUTPUT
          else
            echo "dockerfile_exists=false" >> $GITHUB_OUTPUT
            echo "No Dockerfile.sandbox found in ${{ matrix.project }}, skipping."
          fi

      - name: Set up Docker Buildx
        if: steps.check-dockerfile.outputs.dockerfile_exists == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: steps.check-dockerfile.outputs.dockerfile_exists == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push
        if: steps.check-dockerfile.outputs.dockerfile_exists == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.project }}/Dockerfile.sandbox
          push: true
          tags: |
            safoinext/zenml-sandbox-${{ matrix.project }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
